Repository IAMconsortium/nomenclature, pull requests merged in 2025-01, with the labels that each got.

#450 Pin Poetry version to 1.8
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yml
Labels: bug

#466 Remove None defaults from RegionAggregationMapping
  nomenclature/processor/region.py
  tests/test_region_aggregation.py
Labels: refactor

#456 Specify illegal character(s) found and respective attribute(s)
  nomenclature/codelist.py
  tests/test_codelist.py
Labels: enhancement

#463 Check if constituents of common regions are in native regions
  nomenclature/error.py
  nomenclature/processor/region.py
  tests/data/cli/structure_validation_fails/mappings/mapping_2.yaml
  tests/data/region_processing/external_repo_test/nomenclature.yaml
  tests/data/region_processing/external_repo_test_missing_region/nomenclature.yaml
  tests/data/region_processing/region_aggregation/illegal_mapping_constituent_native_missing.yaml
  tests/test_region_aggregation.py
Labels: bug
